Add commons-logging dependency for PDFBox
PDFBox requires Apache Commons Logging library. This fixes the
NoClassDefFoundError: org/apache/commons/logging/LogFactory error
when clicking the "In PDF" button.